### PR TITLE
Utf8Chunks, serde support, tiny-vec version bump

### PR DESCRIPTION
**Pull request by crat0z**
Changes discussed in #1.

### CODE REVIEW

**Comment by Kl4rry** [comment]
I think the thin-string visitor should implement a few more methods like `visit_stirng`, `visit_bytes` etc like the `String` does in [serde](https://github.com/serde-rs/serde/blob/master/serde/src/de/impls.rs). Otherwise it looks good.

**Comment by crat0z** [comment]
I agree an implementation of `visit_bytes` would be useful. However, from my understanding, `visit_string` and `visit_byte_buf` are only worth implementing if it were possible to take the owned `String` or `Vec<u8>` and construct a `ThinString` without reallocating or copying. I think for that to work, thin-vec would need to be able to convert a `Vec<u8>` to a `ThinVec<u8>` without reallocating, however from [here](https://github.com/Gankra/thin-vec/blob/a0149557282ee78a535d93daaa647668a585569e/src/lib.rs#L2033) that probably isn't possible. Note that the default implementation of both `visit_string` and `visit_byte_buf` just call `visit_str` and `visit_bytes` respectively anyway.

I've pushed another commit with an implementation of `visit_bytes`, but if you'd also like the other methods I can do that as well.

**Comment by crat0z** [comment]
OK, for some extra context: I've looked at some other crates that provide string types, and

- smol_str and compact_str implement all the possible methods, including the 4 mentioned above and also `visit_borrowed_str` + `visit_borrowed_bytes`
- inlinable_string, smallstr and flexstr implement just `visit_str` and `visit_string`

TBH, I'm not even sure when these other methods are used. I thought it would be if the deserializer encounters bytes, but expects a string, the deserializer could try and convert the bytes to a string. So I've tried some common crates that one might use the serde feature for, with this code:
```rs
use serde::{Deserialize, Serialize};
use thin_string::ThinString;

#[derive(Serialize)]
struct ToBytes {
    s: Vec<u8>,
}

#[derive(Deserialize)]
struct FromBytes {
    s: ThinString,
}

fn main() {
    let to = ToBytes {
        s: String::from("hello world").as_bytes().to_owned(),
    };

    let json = serde_json::to_string(&to).unwrap();

    match serde_json::from_str::<FromBytes>(&json) {
        Ok(_) => println!("JSON deserialization works"),
        Err(_) => println!("JSON deserialization doesn't work"),
    }

    let toml = toml::to_string(&to).unwrap();

    match toml::from_str::<FromBytes>(&toml) {
        Ok(_) => println!("TOML deserialization works"),
        Err(_) => println!("TOML deserialization doesn't work"),
    }

    let bincode = bincode::serialize(&to).unwrap();

    match bincode::deserialize::<FromBytes>(&bincode) {
        Ok(_) => println!("bincode deserialization works"),
        Err(_) => println!("bincode deserialization doesn't work"),
    }

    let pot = pot::to_vec(&to).unwrap();

    match pot::from_slice::<FromBytes>(&pot) {
        Ok(_) => println!("pot deserialization works"),
        Err(_) => println!("pot deserialization doesn't work"),
    }
}
```
And the output is identical whether `visit_bytes` is implemented or not. The only one that works is `bincode`, perhaps because it is not "self describing". So yeah, not sure what to do about this

**Comment by Kl4rry** [comment]
If implementing the others have no advantage for thin-string we should only implement `visit_bytes`.

**Pull request merged**
